### ISSUE TITLE
运行短信群发时出现错误

### ISSUE THREAD

**Issue by wenjianmuran** [wenjianmuran/Team-Assistant#48]
```
not well-formed (invalid token): line 10, column 29
Traceback (most recent call last):
  File "msg_tool.py", line 33, in main
    self.login_prepare()
  File "msg_tool.py", line 55, in login_prepare
    Checker.login_prepare(self)
  File "E:\GitHub\Team-Assistant\bin\common.py", line 222, in login_prepare
    self.load_templates()
  File "E:\GitHub\Team-Assistant\bin\common.py", line 230, in load_templates
    self.templates = TemplateParser(self.xml)
  File "E:\GitHub\Team-Assistant\bin\conf.py", line 187, in __init__
    self.validate()
  File "E:\GitHub\Team-Assistant\bin\conf.py", line 208, in validate
    for rmk in __class__.__root(x):
  File "E:\GitHub\Team-Assistant\bin\conf.py", line 202, in __root
    tree = ElementTree.parse(source=f)
  File "C:\Program Files\Python36\lib\xml\etree\ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "C:\Program Files\Python36\lib\xml\etree\ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 10, column 29
2017-10-22 18:01:43,547 INFO    | ========================= 短信工具结束 =========================
2017-10-22 18:03:27,569 INFO    | ========================= 短信工具开始 =========================
2017-10-22 18:03:27,570 ERROR   | not well-formed (invalid token): line 10, column 29
Traceback (most recent call last):
  File "msg_tool.py", line 33, in main
    self.login_prepare()
  File "msg_tool.py", line 55, in login_prepare
    Checker.login_prepare(self)
  File "E:\GitHub\Team-Assistant\bin\common.py", line 222, in login_prepare
    self.load_templates()
  File "E:\GitHub\Team-Assistant\bin\common.py", line 230, in load_templates
    self.templates = TemplateParser(self.xml)
  File "E:\GitHub\Team-Assistant\bin\conf.py", line 187, in __init__
    self.validate()
  File "E:\GitHub\Team-Assistant\bin\conf.py", line 208, in validate
    for rmk in __class__.__root(x):
  File "E:\GitHub\Team-Assistant\bin\conf.py", line 202, in __root
    tree = ElementTree.parse(source=f)
  File "C:\Program Files\Python36\lib\xml\etree\ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "C:\Program Files\Python36\lib\xml\etree\ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 10, column 29
```

**Comment by wenjianmuran** [comment]
检查出错误原因：

短信内容含有XML特殊字符&

解决方案：

在输入时转义，或使用CDATA
