### ISSUE TITLE
踢人并发短信时出现错误

### ISSUE THREAD

**Issue by wenjianmuran** [wenjianmuran/Team-Assistant#49]
```
expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "D:/Documents/GitHub/Team-Assistant/bin/msg_tool.py", line 44, in main
    self.dispel_with_msg()
  File "D:/Documents/GitHub/Team-Assistant/bin/msg_tool.py", line 245, in dispel_with_msg
    self.send_email()
  File "D:\Documents\GitHub\Team-Assistant\bin\common.py", line 390, in send_email
    e.add_attachment(self.XLSX, self.LOG)
  File "D:\Documents\GitHub\Team-Assistant\bin\common.py", line 79, in add_attachment
    with open(file, 'rb') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by wenjianmuran** [comment]
原因分析：
`send_email()`中没有检查附件是否可用就直接添加了
